server.port=8080

tasktracker.max-tasks=100
tasktracker.default-page-size=20

management.endpoints.web.exposure.include=*
logging.level.root=INFO
logging.level.org.example.task_tracker_springboot=DEBUG