server.port=8080

tasktracker.max-tasks=50
tasktracker.default-page-size=10

management.endpoints.web.exposure.include=health
logging.level.root=WARN
logging.level.org.example.task_tracker_springboot=INFO